### PR TITLE
Added the CLAuDE NOM to the repo

### PR DESCRIPTION
**Pull request by TechWizzart**

### CODE REVIEW

**Comment by ReidWeb** [comment]
This may be something to add to a docs folder with the `.tex` files? 🤔

**Comment by arenmarsden** [comment]
> This may be something to add to a docs folder with the `.tex` files?

Maybe some parsing could be done with [Sphinx](https://www.sphinx-doc.org/en/master/)?

**Comment by TechWizzart** [comment]
> This may be something to add to a docs folder with the `.tex` files? 🤔

Yeah that is definitely an option, though if people want to view the manual they are also required to have a working tex installation so maybe we can do both? Have the `.tex` files as the work in progress version and the PDF as the release version?

**Comment by ReidWeb** [comment]
Yeah, would work well to build a "community sourced" user manual IMO.

**Comment by ReidWeb** [comment]
If possible can you change the folder name to `tex-docs` or `docs` or something of the sort, spaces and capital letters aren't particularly user friendly for use in source control due to users on other OS's

**Comment by TechWizzart** [comment]
Fair point, I have updated the name of the folder to cater to users on other OS's. They should now not cause a problem fore anyone.

**Pull request merged**
